name: stage0-plan

on:
  pull_request:
    paths:
      - 'fast/stages/0-org-setup/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fast/stages/0-org-setup

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/660895060666/locations/global/workloadIdentityPools/default/providers/github-default
          service_account: iac-org-cicd-ro@brnfresh-prod-iac-core-0.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - uses: hashicorp/setup-terraform@v3

      - run: gsutil cp gs://brnfresh-prod-iac-core-0-iac-outputs/providers/0-org-setup-ro-providers.tf ./0-org-setup-providers.tf
      - run: terraform init -reconfigure -no-color
      - run: terraform plan -no-color
